version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: runningdash-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=cribldemo1234
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - ./running_dashboard.db:/var/lib/grafana/running_dashboard.db:ro
      - ./dashboard.json:/var/lib/grafana/dashboards/dashboard.json:ro
      - ./provisioning:/etc/grafana/provisioning:ro
